version: '3'
# TODO : prevent the django key from being exposed
services:
  backend:
    build: 
      context: ./back
    ports:
      - "8000:8000"

    # volumes: #//uncomment this if you want to mount the local directory for development
    #   - ./back:/app
    
    #   current directory / to mount in dockerfile "/app"

    networks:
      - wapbox-network
    environment: 
      - DEBUG=False
      - DJANGO_SECRET_KEY=django-insecure-m7c-yxg$z4pbvgd=f@1o_)vv&1daw99ff(a%_x^eg&w!4ynv#d

  frontend:
    build:
      context: ./front
    ports:
      - "3000:3000"
    # volumes: #//uncomment this if you want to mount the local directory for development
    #   - ./front:/app
    depends_on:
      - backend
    networks:
      - wapbox-network

networks:
  wapbox-network:
    driver: bridge