version: '3'
# TODO : prevent the django key from being exposed
services:
  backend:
    build: 
      context: ./back
    ports:
      - "8000:8000"

    # volumes: //uncomment this if you want to mount the local directory for development
    #   - ./back:/app
    networks:
      - wapbox-network
    # environment: # Uncomment this if you want to set environment variables
    #   - DEBUG=True

  frontend:
    build:
      context: ./front
    ports:
      - "3000:3000"
    # volumes: //uncomment this if you want to mount the local directory for development
    #   - ./front:/app
    #   - /app/node_modules
    depends_on:
      - backend
    networks:
      - wapbox-network

networks:
  wapbox-network:
    driver: bridge