services :
  - type: web
    runtime: docker
    name : swapback
    plan : free
    region : singapore
    repo : git@github.com:EsperSaN/WAPBOX.git
    rootDir : back
    envVars :
      - name : PORT
        value : 8080
      - name : DJANGO_SECRET_KEY
        value : "django-insecure-m7c-yxg$z4pbvgd=f@1o_)vv&1daw99ff(a%_x^eg&w!4ynv#d"
      - name : DEBUG
        value : "False"